services:
  - type: web
    name: school-cms
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false       # Render dashboarddan qo'lda kiritiladi
      - key: SESSION_SECRET
        generateValue: true  # Render avtomatik yaratadi
    autoDeploy: true
